services:
  mysql:
    image: mysql:8.4
    container_name: banco-xyz-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: banco_xyz
      MYSQL_USER: banco_user
      MYSQL_PASSWORD: banco_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - banco_xyz_data:/var/lib/mysql

volumes:
  banco_xyz_data: