spring.application.name=banco-xyz-batch

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/banco_xyz
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Batch
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false